type ATokenInstance_Burn {
  id: ID!
  from: String!
  target: String!
  value: BigInt!
  balanceIncrease: BigInt!
  index: BigInt!
}

type ATokenInstance_Mint {
  id: ID!
  caller: String!
  onBehalfOf: String!
  value: BigInt!
  balanceIncrease: BigInt!
  index: BigInt!
}

type ATokenInstance_Transfer {
  id: ID!
  from: String!
  to: String!
  value: BigInt!
}

type FiatTokenV2_2_Burn {
  id: ID!
  burner: String!
  amount: BigInt!
}

type FiatTokenV2_2_Mint {
  id: ID!
  minter: String!
  to: String!
  amount: BigInt!
}

type FiatTokenV2_2_Transfer {
  id: ID!
  from: String!
  to: String!
  value: BigInt!
}

